In [2]:
import numpy as np

Various Array Attributes

In [4]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.shape(a)

(2, 3)

In [6]:
b = np.copy(a).reshape(6,1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [7]:
print(a.itemsize)  ## returns the length of each element of array in bytes

4


In [8]:
print(a.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [9]:
print(b.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



Array Creation Routines

In [11]:
c = np.empty([3,2], dtype = str, order = 'C')     #### dtype can be int(integer), bool(boolean), float, complex, bytes, str, memoryview, etc.
c

array([['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

In [12]:
d = np.zeros([5,2])
d

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
e = np.ones([3,7])
e

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [14]:
E = np.ones_like(e)         #### creates a new array filled with ones, matching the shape and data type of an existing array.
E

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [15]:
f = np.asarray(a, dtype = complex)   ### array() creates a separate copy, while asarray() directly references the original data if possible.
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [16]:
g = np.eye(4, 3)         #### Can create non-square matrices
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [17]:
h = np.identity(4)
h

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
i = np.full([3,2], 3)
i

array([[3, 3],
       [3, 3],
       [3, 3]])

In [19]:
j = np.full_like(i, 2, dtype=int)
j

array([[2, 2],
       [2, 2],
       [2, 2]])

In [20]:
k = [0, 1, 8, 2, 8, 1, 5, 2, 0, 0, 5]
k

[0, 1, 8, 2, 8, 1, 5, 2, 0, 0, 5]

In [21]:
np.asarray(k)      ## converts an input into array.
                    ### Even if the input is already a NumPy array, it creates a copy.

array([0, 1, 8, 2, 8, 1, 5, 2, 0, 0, 5])

In [22]:
np.asanyarray(k)      ## Creates a new array if necessary: If the input is already a NumPy array, it returns a reference to the existing array without copying.
                        ## May convert data type: If the input is not a NumPy array, it tries to convert it to a suitable data type.

array([0, 1, 8, 2, 8, 1, 5, 2, 0, 0, 5])

In [23]:
np.ascontiguousarray(k)    #### ensure that a NumPy array has contiguous memory storage. This means that the elements of the array are stored in a continuous block of memory, which can improve performance for certain operations.

array([0, 1, 8, 2, 8, 1, 5, 2, 0, 0, 5])

In [24]:
np.asmatrix(k)

matrix([[0, 1, 8, 2, 8, 1, 5, 2, 0, 0, 5]])

In [25]:
j.astype(complex)   ### convert the data type of a NumPy array

array([[2.+0.j, 2.+0.j],
       [2.+0.j, 2.+0.j],
       [2.+0.j, 2.+0.j]])

In [26]:
np.frombuffer(j, dtype=int)

array([2, 2, 2, 2, 2, 2])

How to use fromfile 

In [28]:
import tempfile

dt = np.dtype([('time', [('min', np.int64), ('sec', np.int64)]), ('temp', float)])   ## Construct an ndarray
x = np.zeros((1,), dtype=dt)
x['time']['min'] = 10
x['temp'] = 98.5

fname = tempfile.mkstemp()[1]   ## temporary file creation

x.tofile(fname)        ## Save the raw data to disk

In [29]:
np.fromfile(fname, dtype=dt)  ### Read the raw data from disk

array([((10, 0), 98.5)],
      dtype=[('time', [('min', '<i8'), ('sec', '<i8')]), ('temp', '<f8')])

In [30]:
np.save(fname, x)          ### The recommended way to store and load data
np.load(fname + '.npy')

array([((10, 0), 98.5)],
      dtype=[('time', [('min', '<i8'), ('sec', '<i8')]), ('temp', '<f8')])

How to use fromfunction( )

In [32]:
np.fromfunction(lambda i, j: i, (2, 2), dtype=int)  ### it works with i, j indices and returns only i

array([[0, 0],
       [1, 1]])

In [33]:
np.fromfunction(lambda i, j: j, (3, 3), dtype=int)  ### it works with i, j indices and returns only j

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [34]:
np.fromfunction(lambda i, j: i==j, (2, 2), dtype=int)  ### it works with i, j indices and returns only when i==j

array([[ True, False],
       [False,  True]])

In [35]:
np.fromfunction(lambda i, j: i+j, (2, 2), dtype=int)  ### it works with i, j indices and returns the summation of indices

array([[0, 1],
       [1, 2]])

NUMERICAL RANGES

In [37]:
np.arange(-1, 1, 0.5, dtype = float)

array([-1. , -0.5,  0. ,  0.5])

In [38]:
np.linspace(-1, 1, 5)

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [39]:
np.logspace(-1, 1, 5)

array([ 0.1       ,  0.31622777,  1.        ,  3.16227766, 10.        ])

In [73]:
np.geomspace(1, 6, 5)

array([1.        , 1.56508458, 2.44948974, 3.83365863, 6.        ])