ARRAY MANIPULATION ROUTINES

Basic Operations

In [4]:
import numpy as np

In [6]:
a = np.array([1, 2, 3])
B = [4, 5, 6]

In [10]:
np.copyto(a, B)        ### Copies B into a
a

array([4, 5, 6])

In [14]:
np.ndim(a)  ### returns the number of dimensions of an array

1

In [16]:
np.shape(a)        ### returns the shape of an array

(3,)

In [18]:
b = [[3, 2, 1, 7],[4, 9, 0, 2]]
np.shape(b)

(2, 4)

In [20]:
np.size(a)       ### returns the number of elements in a given axis

3

In [22]:
np.size(b)

8

Changing Array Shape

In [29]:
a = np.random.randint(5, 10, (3, 2), dtype=int)
a

array([[7, 8],
       [9, 7],
       [9, 6]])

In [31]:
np.reshape(a, (6, 1))

array([[7],
       [8],
       [9],
       [7],
       [9],
       [6]])

In [39]:
b=np.ravel(a)       ### returns a contiguous flattenned array
print(b)
c=a.reshape(-1)         #### ravel is equivalent to reshape(-1, order=order)
print(c)

[7 8 9 7 9 6]
[7 8 9 7 9 6]


In [41]:
x = np.arange(1, 7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
x.flat[1]        #### 1-D iterator

2

In [49]:
x.T   ### Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [51]:
x.T.flat[2]

2

In [53]:
x.flat = 3
x

array([[3, 3, 3],
       [3, 3, 3]])

In [55]:
x.flat[[1,4]]=1
x

array([[3, 1, 3],
       [3, 1, 3]])

In [59]:
x.flatten()  ### return a copy of the array collapsed into one dimension

array([3, 1, 3, 3, 1, 3])

Transpose-like Operations

In [62]:
y = np.zeros((3,4,5))
y

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [64]:
Y = np.moveaxis(y, 0, -1)
Y

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [66]:
Y.shape

(4, 5, 3)

In [70]:
Y = np.moveaxis(y, -1, 1)
Y.shape

(3, 5, 4)

In [72]:
np.transpose(y).shape

(5, 4, 3)

In [76]:
np.swapaxes(y, 0, -1).shape

(5, 4, 3)

In [78]:
np.moveaxis(y, [0, 1], [-1, -2]).shape

(5, 4, 3)

In [80]:
np.moveaxis(y, [0, 1, 2], [-1, -2, -3]).shape

(5, 4, 3)

Changing Number of Dimensions

In [84]:
a = np.array([[1], [2], [3]])
b = np.array([4, 5, 6])
c = np.broadcast(a, b)
c

In [87]:
d = np.array([1, 2])
d.shape

(2,)

In [89]:
np.expand_dims(d, axis=0)

array([[1, 2]])

In [91]:
np.expand_dims(d, axis=0).shape

(1, 2)

In [93]:
np.expand_dims(d, axis=1).shape

(2, 1)

In [95]:
np.expand_dims(d, axis=(0, 1)).shape

(1, 1, 2)

In [97]:
np.expand_dims(d, axis=(2, 1)).shape

(2, 1, 1)

Joining Arrays

In [104]:
e = np.array([[1, 2], [3, 4]])
f = np.array([[5, 6]])

In [106]:
np.concatenate((e, f), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [110]:
np.concatenate((e, f.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [112]:
np.concatenate((e,f), axis=None)

array([1, 2, 3, 4, 5, 6])

In [114]:
rng = np.random.default_rng()
rng

Generator(PCG64) at 0x2288083BCA0

In [126]:
arrays = [rng.normal(size=(3,4)) for _ in range(10)]  #### creates random 3X4 arrays 10 times
np.stack(arrays, axis=0).shape

(10, 3, 4)

In [128]:
np.stack(arrays, axis=1).shape

(3, 10, 4)

In [130]:
np.stack(arrays, axis=2).shape

(3, 4, 10)